/**
 * Generates out/sw.js after `next build`.
 *
 * The worker must precache the app shell at install time. On a user's very
 * first visit the HTML and JS are fetched before the worker is active, so they
 * never pass through its fetch handler — without an explicit precache, nothing
 * is stored and the next offline load fails. Chunk filenames are content
 * hashed, so the list has to be produced at build time.
 */
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, posix, relative } from "node:path";

const OUT_DIR = "out";
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const full = join(dir, entry.name);
      return entry.isDirectory() ? walk(full) : [full];
    }),
  );
  return files.flat();
}

const all = await walk(OUT_DIR);

const assets = all
  .map((file) => posix.join("/", relative(OUT_DIR, file).split(/[\\/]/).join("/")))
  .filter((url) => !url.endsWith(".map") && url !== "/sw.js" && url !== "/.nojekyll")
  // index.txt is Next's RSC payload; the HTML shell is what we need offline.
  .filter((url) => !url.endsWith("/index.txt"))
  .map((url) => `${BASE_PATH}${url}`)
  .sort();

// Directory-style URL the browser actually requests for the root document.
const shell = `${BASE_PATH}/`;
const precache = [shell, ...assets];

// Any change to the asset list produces a new cache name, which is what
// triggers the activate handler to drop the previous version.
const revision = createHash("sha256").update(precache.join("\n")).digest("hex").slice(0, 12);

const source = `// Generated by scripts/generate-sw.mjs — do not edit.
const CACHE = "expense-tracker-${revision}";
const SHELL = ${JSON.stringify(shell)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // Individually, so one failed asset can't abort the whole install.
      await Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => undefined),
        ),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((name) => name !== CACHE).map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

async function handle(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request, { ignoreSearch: true });

  const network = fetch(request)
    .then((response) => {
      if (response.ok) cache.put(request, response.clone());
      return response;
    })
    .catch(() => null);

  // Cache first: instant, and correct because every asset URL is hashed.
  if (cached) {
    void network;
    return cached;
  }

  const fresh = await network;
  if (fresh) return fresh;

  // Offline and unseen. A page load can still boot from the shell.
  if (request.mode === "navigate") {
    const shell = await cache.match(SHELL);
    if (shell) return shell;
  }
  return Response.error();
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  // Google's OAuth and Drive endpoints must always go to the network.
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith(handle(request));
});
`;

await writeFile(join(OUT_DIR, "sw.js"), source);

const bytes = (
  await Promise.all(assets.map((url) => readFile(join(OUT_DIR, url.slice(BASE_PATH.length)))))
).reduce((total, buffer) => total + buffer.length, 0);

console.log(
  `sw.js: precaching ${precache.length} files (${(bytes / 1024).toFixed(0)} kB), cache expense-tracker-${revision}`,
);
